import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Login } from "./Login/Login"
import React, { useState } from "react"

export default function Home() {
	const [token, setToken] = useState('')
	const handleNewToken = (newToken: string) => {
		setToken(newToken)
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<h1>
					Login
				</h1>
			</header>
			<main>
				{token ? null : <Login onToken={handleNewToken} />}
			</main>
		</div>
	)
}
